---

# Tasks File For Setup
- name: Create database.yml
  template:
    src: templates/database.yml.j2
    dest: "{{app_dir}}/config/database.yml"
  changed_when: false

- name: yarn add
  shell: bash -lc yarn add yarn@1.22.19
  args:
    chdir: "{{app_dir}}"
  changed_when: false

- name: bin/setup
  shell: bash -lc "bin/setup"
  register: setup_result
  args:
    chdir: "{{app_dir}}"
  changed_when: false


- name: bin/rails server -b 0.0.0.0
  ansible.builtin.shell:
    cmd: /bin/bash -lc "bin/railbin/rails server -b 0.0.0.0"
  args:
    chdir: "{{app_dir}}"
  changed_when: false




- name: start puma
  ansible.builtin.service:
    name: puma
    state: restarted
  become: yes







- name: bin/dev
  shell: bash -lc "bin/dev"
  register: dev_result
  args:
    chdir: "{{app_dir}}"
  changed_when: false
