---
##rubyインストール

##rubyがインストール済みか確認
- name: Check ruby installed
  ansible.builtin.command:
    cmd: ruby -v
  register: Check_ruby
  ignore_errors: yes
  changed_when: false

- name: Git ruby-build
  ansible.builtin.git:
    repo: "{{build_git}}"
    dest: "{{rvm_dest}}/plugins/ruby-build"
  when: Check_ruby.failed    ##rubyをインストールしていたらスキップ

##rvmインストールの為の鍵を公式から入手
- name: Import GPG
  ansible.builtin.command: 
    cmd: gpg2 --keyserver keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
  when: Check_ruby.failed
  changed_when: false

- name: Install rvm
  ansible.builtin.shell: 
    cmd: curl -sSL https://get.rvm.io | bash -s stable
  when: Check_ruby.failed
  changed_when: false

##シェルスクリプト上で使えるようにsource処理
- name: Source rvm script
  ansible.builtin.lineinfile:
    path: /home/ec2-user/.bashrc
    line: 'if [ -s $HOME/.rvm/scripts/rvm ] ; then source $HOME/.rvm/scripts/rvm ; fi'
    state: present
  when: Check_ruby.failed
  changed_when: false

- name: Load .bashrc
  ansible.builtin.shell:
    cmd: /bin/bash -lc "source /home/ec2-user/.bashrc"
  when: Check_ruby.failed
  changed_when: false


- name: Rvm ruby
  ansible.builtin.shell:
    cmd: /bin/bash -lc "rvm install ruby-{{ruby_version}}"
  when: Check_ruby.failed
  environment:      ##ansible_env.PATHでリモートアカウントによりパス変更
    PATH: "{{ansible_env.PATH}}:{{rvm_dest}}/bin"
  register: ruby_install
  changed_when: false

- name: ruby version PATH
  ansible.builtin.shell:
    cmd: /bin/bash -lc "rvm use {{ruby_version}}"
  environment:     ##rubyのパスを指定
    PATH: "{{ansible_env.PATH}}:{{rvm_dest}}/bin"
  when: ruby_install.changed




