---
# Tasks File for Ruby
- name: Check Ruby Installed
  shell: bash -lc "ruby -v"
  register: ruby_check
  ignore_errors: true
  changed_when: false

- name: Install rbenv
  git: 
    repo: "{{rbenv_git}}"
    dest: "{{rbenv_dest}}"
  when: ruby_check.failed

- name: Git Ruby-build
  git:
    repo: "{{build_git}}"
    dest: "{{rbenv_dest}}/plugins/ruby-build"
  when: ruby_check.failed

- name: Set rbenv environment
  shell: |
    echo 'export PATH="${HOME}/.rbenv/shims:${HOME}/.rbenv/bin:${PATH}"' >> ${HOME}/.bashrc
    echo 'eval "$(rbenv init -)"' >> ${HOME}/.bashrc
    source ${HOME}/.bashrc
  when: ruby_check.failed


#- name: Makedir
#  shell: mkdir /usr/local/share/ruby-build
#- name: Install Ruby-build
#  shell: ./install.sh
#  args:
#    chdir: "{{rbenv_dest}}/plugins/ruby-build"
#  when: ruby_check.failed
  
#- name: Install Ruby
#  shell: bash -lc "rbenv install {{ruby_version}} -v"
#  when: ruby_check.failed
#  ignore_errors: true

- name: Install ruby
  shell: bash -lc |
    echo "Installing ruby {{ruby_version}}"
    "{{rbenv_dest}}/bin/rbenv install {{ruby_version}}"
    "{{rbenv_dest}}/bin/rbenv global {{ruby_version}}"
    "{{rbenv_dest}}/bin/rbenv rehash" 
  when: ruby_check.failed
  ignore_errors: true

#- name: Global Ruby
#  shell: bash -lc "{{rbenv_dest}}/bin/rbenv global {{ruby_version}}"
#  when: ruby_check.failed
#  ignore_errors: true

#- name: Rehash Ruby
#  shell: "{{rbenv_dest}}/bin/rbenv rehash"
#  when: ruby_check.failed
#  ignore_errors: true

#- name: Global Ruby Version
#  debug:
#    var: ruby_check
#  ignore_errors: true
#  when: ruby_check.failed
