AWSTemplateFormatVersion: "2010-09-09"

Description: VPC and subnets for RaiseTech-Lecture13


## Metadataの作成 ##
Metadata:
  AWS::CloudFormation::Interface:    
    ParameterGroups:
      - Label:    #パラメーターの名前
          default: Environment Setting
        Parameters:
          - ProjectName
      - Label:
          default: Network Configuration
        Parameters:
          - VPCCIDR　#VPCのCDIR(デフォルト値は以下で指定)
          - PublicSubnetACIDR
          - PublicSubnetCCIDR
          - PrivateSubnetACIDR
          - PrivateSubnetCCIDR


## Parametersの作成 ##

Parameters:      
  ProjectName:
    Type: String
    Description: Project Name
    Default: RaiseTech-Lec13
  VPCCIDR:
    Type: String
    Default: 10.1.0.0/16
  PublicSubnetACIDR:
    Type: String
    Default: 10.1.10.0/24
  PublicSubnetCCIDR:
    Type: String
    Default: 10.1.20.0/24
  PrivateSubnetACIDR:
    Type: String
    Default: 10.1.100.0/24
  PrivateSubnetCCIDR:
    Type: String
    Default: 10.1.200.0/24


Resources:

## VPCの作成 ##
 
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-vpc

## InternetGatewayの作成 ##

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-igw

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

## Subnetの作成 ##

  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: ""
      CidrBlock: !Ref PublicSubnetACIDR
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-PubSubA

  PublicSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 1
        - Fn::GetAZs: ""
      CidrBlock: !Ref PublicSubnetCCIDR
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-PubSubC

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select 
        - 0
        - Fn::GetAZs: ""
      CidrBlock: !Ref PrivateSubnetACIDR
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-PriSubA

  PrivateSubnetC:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select 
        - 1
        - Fn::GetAZs: ""
      CidrBlock: !Ref PrivateSubnetCCIDR
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-PriSubC


## RouteTableの作成 ##

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-PublicRouteTable

  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-PrivateRouteTable1

  PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-PrivateRouteTable2

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway


## Associate Routetable with Subnet　##

  PublicSubnetRouteATableAssociation:       
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref PublicRouteTable

  PublicSubnetRouteCTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetC
      RouteTableId: !Ref PublicRouteTable

  PrivateSubnetRouteATableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetA
      RouteTableId: !Ref PrivateRouteTable1

  PrivateSubnetRouteCTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetC
      RouteTableId: !Ref PrivateRouteTable2

## Outputsの作成 ##
Outputs: 
  vpcId: 
    Value: !Ref VPC
    Export:
      Name: VPCID

  PublicSubnetAId:
    Value: !Ref PublicSubnetA
    Export:
      Name: Pub-SubA-ID

  PublicSubnetCId:
    Value: !Ref PublicSubnetC
    Export:
      Name: Pub-SubC-ID

  PrivateSubnetAId:
    Value: !Ref PrivateSubnetA
    Export: 
      Name: Pri-SubA-ID

  PrivateSubnetCId:
    Value: !Ref PrivateSubnetC
    Export: 
      Name: Pri-SubC-ID




