---
#アプリケーションダウンロード

- name: Check In App
  stat: path= "{{app_dir}}"
  register: Check_App

- name: Git App
  git: 
    repo: "{{repo_url}}"
    dest: "{{app_dir}}"  
    force: yes
  when: Check_App.stat.exists == false

- name: Git Message
  debug: 
    msg: "既にRailsアプリケーションはクローン済みです"
  when: Check_App.stat.exists == true
