---
#アプリケーションダウンロード

- name: Check In App
  stat:
    path: "{{app_dir}}"
  register: Check_App
  ignore_errors: true

- name: Git App
  git: 
    repo: "{{repo_url}}"
    dest: "{{app_dir}}"  
#  when: (Check_App.stat.exists == true).skipp
  when: Check_App == null

- name: Git Message
  debug:
    msg: "既にRailsアプリケーションはクローン済みです"
  when: Check_App.stat.exists
