---
#アプリケーションダウンロード

- name: Check In App
  stat: path= "{{app_dir}}"
  register: Check_App


#- name: Check In App 2
#  shell: bash -lc ls -l | grep raisetech-live8-sample-app
#  register: raisetech


- name: Git App
  git: 
    repo: "{{repo_url}}"
    dest: "{{app_dir}}"  
  ignore_errors: true
  when: not Check_App.stat.exists

- name: Git Message
  debug: 
    msg: "既にRailsアプリケーションはクローン済みです"
  when: Check_App.stat.exists
