---
#アプリケーションダウンロード

- name: Check In App
  shell: bash -lc ls -l | grep "{{app_name}}/asdf"
  register: Check_App


- name: Git App
  git: 
    repo: "{{repo_url}}"
    dest: "{{app_dir}}/asdf"  
  ignore_errors: true
  when: Check_App is false

