---
#アプリケーションダウンロード

- name: Check In App
  debug:
    msg "test{{asdf}}"

#  stat: path= "{{app-dir}}"
#  register: Check_app

- name: Git App
  git: 
    repo: "{{repo_url}}"
    dest: "{{user_dir}}"  
  when: Check_app.stat.exists

- name: Git Message
  debug: 
    msg: "既にRailsアプリケーションはクローン済みです"
  when: Check_App.stat.exists
