---
#アプリケーションダウンロード

- name: Check In App
  stat: path="{{app_dir}}"
  register: a

- name: Git App
  git: 
    repo: "{{repo_url}}"
    dest: "{{user_dir}}"  
  when: not a.stat.exists

- name: Git Message
  debug:
    msg: "既にRailsアプリケーションはクローン済みです"
  when: Check_App.stat.exists
