version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.1.0

jobs:
  execute-cloudformation:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          aws_access_key_id: AWS_ACCESS_KEY_ID
          aws_secret_access_key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
      - run: 
          name: Deploy to was from template
          command: |
            set -x
            aws cloudformation deploy --template cloudformation/vpc.yml --stack-name CircleCI-lec13-vpc
            aws cloudformation deploy --template cloudformation/security.yml --stack-name CircleCI-lec13-security
            aws cloudformation deploy --template cloudformation/security.yml --stack-name CircleCI-lec13-security

workflows:
  circleci-raisetech13-workflow:
    jobs:
      - execute-cloudformation

