---
# Tasks File for Ruby
- name: 'Check Ruby Installed'
  shell: bash -lc "rbenv --version"
  register: ruby_check
  ignore_errors: true
  changed_when: false

- name: Ruby Version
  debug:
    var: ruby_check 
  ignore_errors: true
  changed_when: false

- name: 'Install rbenv'
  git: repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv
  when: ruby_check.failed

- name: 'Bash Write'
  shell: |
    echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
    echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
    source ~/.bash_profile
  when: ruby_check.failed

- name: 'Git Ruby-build'
  git: repo=https://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build
  when: ruby_check.failed

- name: 'Install Ruby-build'
  shell: ./install.sh
  args:
    chdir: ~/.rbenv/plugins/ruby-build
  when: ruby_check.failed

- name: 'Install Ruby'
  shell: bash -lc "rbenv install {{ruby_version}} -v"
  when: ruby_check.failed
  ignore_errors: true

- name: 'Global Ruby'
  shell: bash -lc "rbenv global {{ruby_version}}"
  when: ruby_check.failed
