---
# tasks file for ruby
- name: Check if ruby is installed
  command: ruby --version
  register: ruby_check
  ignore_errors: true
  changed_when: false

- name: 'Install rbenv'
  git: repo=https://github.com/sstephenson/rbenv.git dest=~/.rbenv
  when: ruby_check.failed

- name: 'bashの読み込み'
  shell: echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
  shell: echo 'eval "$(rbenv init -)"' >> ~/.bash_profile
  shell: source ~/.bash_profile
  when: ruby_check.failed

- name: 'Install ruby-build'
  git: repo=https://github.com/sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build
  when: ruby_check.failed

- name: 'bashの実行'
  shell: ./install.sh
  when: ruby_check.failed

- name: 'rubyのインストール'
  command: rbenv install 3.2.3 -v
  when: ruby_check.failed

- name: 'rubyのグローバル設定'
  command: rbenv global 3.2.3
  when: ruby_check.failed
