---
- name: Uninstall mysql-server
  become: yes
  yum:
    name: mysql-server
    state: absent

- name: Uninstall mariaDB
  become: yes
  yum:
    name: mariadb*
    state: absent

- name: Add the MySQL from YumRepository
  become: yes
  yum:
    name: https://repo.mysql.com/mysql84-community-release-el7-1.noarch.rpm
    state: present

- name: Install mysql-community-devel
  become: yes
  yum:
    name: mysql-community-devel
    state: present

- name: Install mysql-community-server
  become: yes
  yum:
    name: mysql-community-server
    state: present


