---
# Nginxのインストール

- name: Enable Amazon-linux-extras
  command: amazon-linux-extras install epel -y
  args:
    creates: /etc/yum.repos.d/epel.repo

- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Ensure Nginx is started and enabled on boot
  systemd:
    name: nginx
    state: started
    enabled: true

