---
#Task File For Bundler

- name: Check Bundler Installed
  command: bundler _{{bundler_version}}_ --version
  register: bundler_check
  ignore_errors: true
  changed_when: false

- name: Install Bundler Viersion
  shell: export "BUNDLER_VERSION={{bundler_version}}"
  when: bundler_check.failed

- name: Install Bundler
  shell: bash -lc "gem install bundler -v {{bundler_version}}" 
  when: bundler_check.failed

#- name: Install Bundler
#  gem:
#    name: bundler
#    state: present
#    executable: "{{rbenv_dest}}/shims/gem"
#    user_install: false
#    version: "{{bundler_version}}"
#  when: bundler_check.failed
