---
##Gem bundler

##bundlerインストールのチェック
- name: Check bundler
  ansible.builtin.command:
    cmd: '~/.rvm/gems/ruby-3.2.3/bin/bundler -v'
  register: Check_bundler
  ignore_errors: yes
  changed_when: false

- name: Install viersion(bundler)
  ansible.builtin.shell:
    cmd: export "BUNDLER_VERSION={{bundler_version}}"
  when: Check_bundler.failed

- name: Gem bundler
  ansible.builtin.shell:
    cmd: bash -lc "gem install bundler -v {{bundler_version}}" 
  when: Check_bundler.failed

