---
- name: Setup nginx server on myserver list (host group)
  hosts:
    - targetservers
  become: True
  tasks:
    - name: Install the latest version of nginx
      command: dnf install -y nginx

    - name: Start nginx service
      service:
        name: nginx
        state: started

    - name: Enable nginx service
      service:
        name: nginx
        enabled: yes

    - name: Get nginx Installed version
      command: nginx -v

    - name: Get status of nginx service
      command: systemctl status nginx

