---
# Tasks File For Node
- name: Check Installed Node
  command: node -v
  register: node_check
  ignore_errors: true
  changed_when: false

- name: Install nvm
  shell: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash"
  when: node_check.failed
  changed_when: false

- name: Load Bash
  shell: source ~/.bashrc
  when: node_check.failed

- name: Install Node
  shell: bash -lc "nvm install {{node_version}}"
  when: node_check.failed

