---
- hosts: all
  become: yes
  tasks:
    - name: Install git
      yum:
        state: present
        lock_timeout: 180

    - name: Install necessary packages
      yum:
        name:
          - make
          - gcc-c++
          - patch
          - openssl-devel
          - libyaml-devel
          - libffi-devel
          - libicu-devel
          - libxml2
          - libxslt
          - libxml2-devel
          - libxslt-devel
          - zlib-devel
          - readline-devel
          - ImageMagick
          - ImageMagick-devel
          - epel-release
          - nc
        state: present #削除する場合はabsent
