---
- hosts: all
  become: yes

  vars:
    aws_db_pw: "{{ (lookup('env','AWS_DB_PW')) }}"
    rds_endpoint: "{{ (lookup('env','RDS_ENDPOINT')) }}"   

  roles:
    - swap
    - git
    - app-in
    - yum
    - mysql
    - ruby
    - rails
    - bundler
    - node
    - yarn
    - imagemagick
    - nginx
    - setup
    - setup_server
