---
- hosts: all
  become: yes

  vars:
    aws_db_pw : "{{ (lookup('env','AWS_DB_PW')) }}"

  roles:
    - swap
    - git
    - app-in
    - yum
    - mysql
    - ruby
    - rails
    - bundler
    - node
    - yarn
    - imagemagick
    - setup
#    - nginx

