---
- name: Create Swapfile
- set_fact:
    swap_file_path: /swapfile
- command: dd if=/dev/zero of={{ swap_file_path }} bs={{ ansible_memtotal_mb }} count=2M
  args:
    creates: '{{ swap_file_path }}'
- file:
    path: '{{ swap_file_path }}'
    mode: '0600'
- command: file {{ swap_file_path }}
  register: swap_file_test
- command: mkswap {{ swap_file_path }}
  when: ansible_swaptotal_mb == 0
- command: swapon {{ swap_file_path }}
  when: ansible_swaptotal_mb == 0
- mount:
    name: swap
    src: '{{ swap_file_path }}'
    fstype: swap
    opts: defaults
    passno: '0'
    dump: '0'
    state: present
- name: start swapfile.swap
  systemd:
    name: swapfile.swap
    state: restarted
    daemon_reload: yes
    enabled: yes




    lock_timeout: 180

